# Generated by Django 5.2.1 on 2025-05-30 16:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judulFilm', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=25)),
                ('deskripsi', models.TextField()),
                ('ratingUsia', models.CharField(max_length=10)),
                ('durasi', models.IntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='poster/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nama', models.CharField(max_length=25)),
                ('noTelepon', models.IntegerField(unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jamTayang', models.TimeField()),
                ('namaBioskop', models.CharField(blank=True, max_length=20, null=True)),
                ('jenisStudio', models.CharField(blank=True, max_length=20, null=True)),
                ('studio', models.CharField(max_length=10)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesantiket.film')),
            ],
        ),
        migrations.CreateModel(
            name='Kursi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomorKursi', models.CharField(max_length=5)),
                ('status', models.BooleanField(default=False)),
                ('harga', models.FloatField()),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesantiket.jadwal')),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggalPemesanan', models.DateField(auto_now_add=True)),
                ('totalHarga', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesantiket.jadwal')),
                ('kursi', models.ManyToManyField(to='pesantiket.kursi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodePembayaran', models.CharField(max_length=50)),
                ('pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesantiket.pemesanan')),
            ],
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeTiket', models.CharField(max_length=20, unique=True)),
                ('jamTayang', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('kursi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesantiket.kursi')),
                ('pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesantiket.pemesanan')),
            ],
        ),
    ]
