# Generated by Django 5.2.1 on 2025-05-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesantiket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='noTelepon',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
